// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvseuixaarwrawudrxhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2c2V1aXhhYXJ3cmF3dWRyeGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1OTg5NzksImV4cCI6MjA1NzE3NDk3OX0.1egIdzZ4w-A2QHDp8uAYvstfO25MCjs-GGkhici_mSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);